baseURL = 'https://blog.flomb.net'
languageCode = 'en-us'
title = 'Flomb Blog'
theme = 'holy'
#publishDir = 'docs'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe= true  